README.md

The following warning occurred in the script in README.md:
% ruby -v -W -e 'Dir.mkdir("out") unless File.exists?("out")'
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
-e:1: warning: File.exists? is a deprecated name, use File.exist? instead
I tried not to use a deprecated method.

Don't use deprecated method

---

README.md
bin/htmlproof
lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/check_runner/issue.rb
lib/html/proofer/checkable.rb
lib/html/proofer/checks/favicon.rb
lib/html/proofer/checks/html.rb
lib/html/proofer/checks/images.rb
lib/html/proofer/checks/links.rb
lib/html/proofer/checks/scripts.rb
lib/html/proofer/url_validator.rb
spec/html/proofer/command_spec.rb
spec/html/proofer/favicon_spec.rb
spec/html/proofer/html_spec.rb
spec/html/proofer/images_spec.rb
spec/html/proofer/links_spec.rb
spec/html/proofer/scripts_spec.rb
spec/html/proofer_spec.rb
spec/spec_helper.rb

Fixes https://github.com/gjtorikian/html-proofer/issues/138.

Add support for `checks_to_ignore`

---

lib/html/proofer.rb
spec/html/proofer/fixtures/links/folder/multiples/catalog/file.html
spec/html/proofer/fixtures/links/folder/multiples/javadoc/file.html
spec/html/proofer_spec.rb
spec/spec_helper.rb

Fixes https://github.com/gjtorikian/html-proofer/issues/145.
~~Not sure why `each` didn't work in this case. Very strange.~~ A premature `return` was causing the `each` loop to short circuit. Sneaky!

Proper iteration over multiple file ignores

---

lib/html/proofer/url_validator.rb
spec/html/proofer/fixtures/links/redirected_error.html
spec/html/proofer/links_spec.rb

Fixes https://github.com/gjtorikian/html-proofer/issues/77, I think. We'll do a re-request with the original URL, rather than the assumed one.

Report errors on original href, maybe

---

lib/html/proofer/check_runner.rb
lib/html/proofer/check_runner/issue.rb
lib/html/proofer/checkable.rb
lib/html/proofer/checks/images.rb
lib/html/proofer/checks/links.rb
lib/html/proofer/checks/scripts.rb
lib/html/proofer/url_validator.rb
spec/html/proofer/scripts_spec.rb
spec/html/proofer_spec.rb

Should close https://github.com/gjtorikian/html-proofer/issues/146 when it's ready.

Add basic line number support

---

lib/html/proofer/checkable.rb

`htmlproof --check-html` tries to call CGI.unescape, which is not in scope
at the moment.

Add missing cgi dependency

---

lib/html/proofer/checks/links.rb
spec/html/proofer/fixtures/links/invalid_mailto_link.html
spec/html/proofer/links_spec.rb

Related to #173 I reduced the amount of checks.

Speed up the mailto check

---

lib/html/proofer.rb

This pull request sets the default user agent as `Mozilla/5.0 (compatible; HTML Proofer/2.1.0}; +https://github.com/gjtorikian/html-proofer)`. The user agent screen is based off of GoogleBot's user agent format. This should allow us to bypass Typhoeus-specific blocks on WordPress and Drupal.
Via @gjtorikian over in https://github.com/gjtorikian/html-proofer/issues/200#issuecomment-94313702:
> What are the ethics involved in my changing the User-Agent to something non-static to avoid being blacklisted again?
I believe as long as we're honest, and identify as HTML-Proofer (which can be blocked if that is in fact the desired behavior), we're fine. I don't think we should e.g., have a random string as a user agent hash. I suspect the services are blocking Typhoeus to prevent scraping, which …

Set default user agent

---

.travis.yml

* Use the container-based infra which usually has a shorter queue 
* Cache gems between builds

Faster Travis builds

---

bin/htmlproof

this avoids the problem when there's more than one colon in the string, to split it into more pieces
around the same code, there is a situation when the string is surrounded by // that needs to be solved
it is converted into a regular expression, and then the split method is not available and the application breaks.
thank you

only split into two

---

lib/html/proofer.rb
script/bootstrap

@benbalter Ugh so dumb. Since [the test](https://github.com/gjtorikian/html-proofer/blob/14edbcaaee5dc078f1d4c7ae938e553174741ba7/spec/html/proofer/links_spec.rb#L79-L83) was passing in its own Typhoeus options, it overwrote the User-Agent option. 
This PR changes things to keep the UA change while still respect other key changes.
Closes https://github.com/gjtorikian/html-proofer/issues/200.

Better Typhoeus option handling

---

lib/html/proofer/checks/images.rb
spec/html/proofer/fixtures/images/emptyImageAltText.html
spec/html/proofer/images_spec.rb

This better handles a malicious `alt="    "` case.

Strip whitespace from empty `alt` tags

---

README.md
bin/htmlproof
lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/checkable.rb
lib/html/proofer/checks/images.rb
spec/html/proofer/command_spec.rb
spec/html/proofer/fixtures/images/emptyImageAltText.html
spec/html/proofer/images_spec.rb

Companion to https://github.com/gjtorikian/html-proofer/pull/196. I'll use this branch to push up changes and get it merged in.

Add --ignore-empty-alt

---

README.md

I forgot to call the `run` method.

Fix the insecure example

---

README.md

Code in the README with regards to changing the user agent is missing a closing curly bracket. 
Should read:
``` ruby
HTML::Proofer.new("out/", {
:typhoeus => {
:headers => { "User-Agent" => "Mozilla/5.0 (compatible; My New User-Agent" }
}}).run
```
Fix in pull request.

corrected code snippet missing curly bracket

---

README.md
lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/checkable.rb
spec/html/proofer/checkable_spec.rb
spec/html/proofer/fixtures/scripts/ignorableLinksViaOptions.html
spec/html/proofer/scripts_spec.rb

Fix #211 
From what I feel `href_ignore` should work on all checkable elements. I don’t think we want dedicated ignores for every possible attribute, like `src_ignore`, `srcset_ignore`, etc.

Make href_ignore work on all elements

---

lib/html/proofer/checkable.rb
lib/html/proofer/checks/scripts.rb
spec/html/proofer/checkable_spec.rb

This fixes the bug noticed in https://github.com/gjtorikian/html-proofer/issues/213#issuecomment-99411107

Accept the content attribute

---

.travis.yml
Gemfile
README.md
spec/spec_helper.rb

Looks like we don’t use Codeclimate.

Removed Codeclimate

---

lib/html/proofer/checks/html.rb
spec/html/proofer/html_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/232.

Add line numbers to failing HTML checks

---

bin/htmlproof

Wasn't able to use `--ignore-script-embeds` on the command line.  This should fix that.

correct ignore script option

---

README.md
bin/htmlproof
lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/checkable.rb
lib/html/proofer/checks/favicon.rb
lib/html/proofer/checks/html.rb
lib/html/proofer/checks/images.rb
lib/html/proofer/checks/links.rb
lib/html/proofer/checks/scripts.rb
lib/html/proofer/log.rb
lib/html/proofer/url_validator.rb
lib/html/proofer/utils.rb
spec/html/proofer/fixtures/links/check_just_once.html
spec/html/proofer/fixtures/vcr_cassettes/links/check_just_once_html.yml
spec/html/proofer/fixtures/vcr_cassettes/sorting/status_verbosity_info_typhoeus_followlocation_false_error_sort_status_.yml
spec/html/proofer/links_spec.rb
spec/html/proofer/utils_spec.rb
spec/html/proofer_spec.rb
spec/spec_helper.rb

This loosens up the external URL checks for URLs with queries. For example:
``` html
<a href="https://github.com/contact?form%5Bsubject%5D=New+Assigned+Events">First</a>
<a href="https://github.com/contact?form%5Bsubject%5D=Organization+and+Team+Membership+APIs">Ignored</a>
<a href="https://github.com/contact#false?form%5Bsubject%5D=Organization+and+Team+Membership+APIs">Second, because of hash</a>
<a href="https://github.com/contact?form%5Bsubject%5D=Blah+and+blah+blah+APIs">Ignored</a>
```
It doesn't matter that `contact?form` has multiple values. The URL is essentially the same.
In this PR, we'll consider a URL with queries different if and only if it has different query parameters, not different query values.

Loosen up query check

---

lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/url_validator.rb
spec/html/proofer/links_spec.rb

It doesn't make sense to keep this functionality in CheckRunner, mostly because UrlValidator deals with *all* the URLs, whereas CheckRunner is picked up on every single file read.

Move query string check inline into UrlValidator

---

lib/html/proofer/check_runner.rb
lib/html/proofer/checkable.rb
lib/html/proofer/url_validator.rb
spec/html/proofer/checkable_spec.rb
spec/html/proofer/fixtures/html/invalid_attribute.html
spec/html/proofer/fixtures/links/bad_external_links.html
spec/html/proofer/fixtures/vcr_cassettes/links/bad_external_links_html.yml
spec/html/proofer/fixtures/vcr_cassettes/www_github_com_http_/127_0_0_1_____.yml
spec/html/proofer/links_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/248 -- invalid URLs should be reported, but not raise exceptions. 
Closes https://github.com/gjtorikian/html-proofer/issues/245 by allowing `.` to be escaped.

Do not explode on error

---

bin/htmlproof

This fixes issue that '--ignore_script_embeds' is not passed through correctly when using CLI.
Related to: https://github.com/gjtorikian/html-proofer/pull/234#issuecomment-142422742

Fixed --ignore_script_embeds argument when passed through CLI

---

bin/htmlproof
html-proofer.gemspec

This fixes https://github.com/gjtorikian/html-proofer/issues/258, in that the built gem should only include the files in `lib` and `bin`, thus omitting the Git check on every `htmlproof` run.

Don't bundle everything up in the gem

---

README.md
bin/htmlproof
lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/checkable.rb
lib/html/proofer/checks/links.rb
spec/html/proofer/command_spec.rb
spec/html/proofer/fixtures/links/hash_href.html
spec/html/proofer/links_spec.rb

Fixes #255 by adding a more intuitive option to allow the `href` `#`.
This option, `--allow-hash-href`, is equivalent to `--href-ignore '#'`.
Its Ruby option is `allow_hash_href`, which should be a boolean and
defaults to `false`.

Added --allow-hash-href option

---

README.md
lib/html/proofer.rb

It appears that on OS X, the default concurrency of 200 simply stops functioning after some time. The [Typhoeus docs even note](https://github.com/typhoeus/typhoeus/tree/c624a57477c07f32d48154ad5a656f699f4db13e#specifying-max-concurrency) this:
> Things will get flakey if you try to make too many requests at the same time. 
Setting a default limit of 50 slows things down a bit, but results in more accurate results.
Closes https://github.com/gjtorikian/html-proofer/issues/253

Set `max_concurrency` to `50`

---

README.md

I spent a few mins looking up how to exclude URLs with regex, although probably people more familiar with Ruby won't have that issue.

Regex example for clarity

---

lib/html/proofer/utils.rb
spec/html/proofer/fixtures/html/weird_iframe.html
spec/html/proofer/fixtures/html/weird_onclick.html
spec/html/proofer/fixtures/vcr_cassettes/html/weird_onclick_html_check_html_true_.yml
spec/html/proofer/html_spec.rb

Apparently, unescaped forward slashes or ampersands will cause Nokogiri to break. In these cases, it's best to just rewrite the content so that Nokogiri is happy.
I thought about performing this rewrite for only HTML validation cases, but it felt better to just always do a clean.
Closes https://github.com/gjtorikian/html-proofer/issues/267.

Clean content before parsing with Nokogiri

---

README.md
bin/htmlproof
lib/html/proofer.rb
lib/html/proofer/configuration.rb
spec/html/proofer/command_spec.rb

For too long, too many config options have been either poorly documented or completely missing from the `htmlproof` executable. 
This PR adds a test to ensure that the docs and options are in sync.

Unify configuration between README and executable

---

lib/html/proofer/checks/html.rb
lib/html/proofer/utils.rb
spec/html/proofer/fixtures/html/normal_looking_page.html
spec/html/proofer/fixtures/vcr_cassettes/html/normal_looking_page_html_check_html_true_.yml
spec/html/proofer/html_spec.rb

It seems that Nokogiri is overly strict and any attempt to change its strictness is not really working out.
This PR quasi reverts changes in https://github.com/gjtorikian/html-proofer/pull/273, in that it simply ignores the error instead of rewriting content.
Related to https://github.com/github/government.github.com/pull/423.

Fix attempts at cleaning content

---

README.md
bin/htmlproof
lib/html/proofer.rb
lib/html/proofer/check_runner.rb
lib/html/proofer/checkable.rb
lib/html/proofer/checks/favicon.rb
lib/html/proofer/checks/images.rb
lib/html/proofer/checks/links.rb
lib/html/proofer/checks/scripts.rb
lib/html/proofer/configuration.rb
spec/html/proofer/command_spec.rb
spec/html/proofer/favicon_spec.rb
spec/html/proofer/fixtures/vcr_cassettes/www_garbalarba_com_url_swap_/garbalarba/_github_.yml
spec/html/proofer/images_spec.rb
spec/html/proofer/links_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/219, closes https://github.com/gjtorikian/html-proofer/issues/214.
The URL versions are more generic, and should act on more than just `href` elements.

Drop href ignore/swap in favor of url ignore/swap

---

lib/html/proofer/checks/links.rb
spec/html/proofer/fixtures/links/blank_href_html4.html
spec/html/proofer/fixtures/links/blank_href_html5.html
spec/html/proofer/fixtures/links/blank_href_htmlunknown.html
spec/html/proofer/links_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/254.

Allow HTML5 anchors to not need `href`

---

README.md
bin/htmlproof
lib/html/proofer/checkable.rb
lib/html/proofer/configuration.rb
spec/html/proofer/fixtures/links/no_html_extension.html
spec/html/proofer/links_spec.rb

To support Jekyll 3 and github pages, which automatically deliver `/example.html` if `/example` is requested. Code is cribbed from @parkr's code in #221. I'm not finished with this yet, though it works and I'm using it to test my Jekyll 3 site. 
Still to do is to make this optional behaviour, so it doesn't affect existing users unless they turn it on.
@parkr @gjtorikian, any insight you might have into why #221 was dropped (and therefore what might need fixing to get it accepted) would be lovely.
Resolves #309.

Allow extensionless URLs

---

bin/htmlproofer

`ignored_status_codes.include? 429` will be false if `ignored_status_codes = ["429"]`

htmlproofer should set status codes to ints

---

lib/html-proofer/url_validator.rb
spec/html-proofer/cache_spec.rb

Message can be populated and useful to know. I've only seen in execution environment I can't control (CI) and [want](https://github.com/github/choosealicense.com/pull/374) to see additional feedback. https://github.com/gjtorikian/html-proofer/issues/299#issuecomment-194754495 shows someone else's example of this. But apparently (#321) others see status code 0 when run locally and wonder what's wrong.
Unresolvable host is one status code 0 message that I can produce easily. I haven't added a test for this as an expected message because I haven't figured out how to have test output not recorded, or recorded with message -- 2nd time new test (not in this PR) is run without deleting recording, there is no message, so test fails.

Show return message for status code 0

---

lib/html-proofer/check/images.rb
lib/html-proofer/element.rb
spec/html-proofer/fixtures/vcr_cassettes/images/ignorableAltViaOptions_html_alt_ignore_/wikimedia/_gpl_png_log_level_error_type_file_.yml
spec/html-proofer/fixtures/vcr_cassettes/images/srcSetIgnorable_html_alt_ignore_/wikimedia/_gpl_png_log_level_error_type_file_.yml
spec/html-proofer/images_spec.rb

* alt_ignore for an image does not ignore the whole image now. If it is missing, it will be reported.
* Also, this unearthed another issue, where srcset was not properly 'fixed' by prefixing it with http://.
Just so it is clear, without this change, any image that was alt_ignored-d, was ignored [here](https://github.com/gjtorikian/html-proofer/blob/0669699e8eb575456db97cfe6246591e37718e25/lib/html-proofer/check/images.rb#L21) in the checking process, and so, if the image it referred to is missing, the issue wouldn't be added to the final result.

Properly ignore alt without ignoring image

---

README.md

Text hyperlinked to Nokogiri changed.

Text update of Nokogiri hyperlink

---

README.md

I have heard some people being interested in the project but having difficulties with the installation...decided to wrap it up in a Docker image.

link to html-proofer-docker

---

README.md
bin/htmlproofer
spec/html-proofer/command_spec.rb

Fixed #293 by adding `\\` and `\:` as escape sequences for the
`--url-swap` flag. This allows command line users the same
expressiveness as Ruby users.

Added escape sequences for --url-swap

---

README.md
bin/htmlproofer
spec/html-proofer/command_spec.rb
spec/html-proofer/fixtures/links/linkTranslatedViaHrefSwap2.html

This replaces the detection of escaped colons to a regex, thereby voiding the need to escape backslashes.
Add test and fixture for an escaped colon.

Use regex for colon escape

---

README.md
bin/htmlproofer
lib/html-proofer/runner.rb
spec/html-proofer/command_spec.rb
spec/html-proofer/fixtures/links/linkTranslatedInternalDomains.html
spec/html-proofer/links_spec.rb

Adds an option to treat certain domains as internal.
Any domains specified will be removed from URLs via the url_swap feature.
Closes #349

Add --internal-domains option

---

lib/html-proofer/check.rb
lib/html-proofer/element.rb
spec/html-proofer/element_spec.rb
spec/html-proofer/fixtures/images/relativeWithBase.html.html
spec/html-proofer/fixtures/links/relativeLinksWithBase.html
spec/html-proofer/images_spec.rb
spec/html-proofer/links_spec.rb

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)
> The **HTML `<base>` element** specifies the base URL to use for all relative URLs contained within a document.
Successor to https://github.com/gjtorikian/html-proofer/pull/265, closes #166.
/cc @bkeepers

Add support for `base` element

---

README.md

Documented on command line at https://github.com/gjtorikian/html-proofer/blob/a1f33c14b3e5523bc6ba4a4cef54869f57f98037/bin/htmlproofer#L24 but not in readme.

Add check_img_http to README

---

spec/html-proofer/opengraph_spec.rb

Or maybe a [fluke](https://github.com/gjtorikian/html-proofer/pull/372#issuecomment-273313963)? Sending this in case not, did before noticing linked comment. Ignore if useless. :smile:

test url maybe once obtained 406, now 404

---

html-proofer.gemspec
lib/html-proofer.rb
lib/html-proofer/check/links.rb
spec/html-proofer/links_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/389.
Unfortunately, there's no way to assert if a domain is valid or not when it's marked up as `dns-prefetch`. The attribute provides numerous benefits to the user, so I don't want these to mark as false positive.
It is entirely possible for someone to provide a bogus URL here. But, since this is largely confined to how a browser behaves and is not related to a user experience, I am fine trading correctness for performance in this case.

Skip DNS prefetch links for now

---

lib/html-proofer/url_validator.rb
spec/html-proofer/links_spec.rb

Typheous unfortunately occasionally adds an extra slash when it attempts
to check external URLs. This change at least removes that slash from
the URL to make future grepping easier, if not 100% accurate.
Closes https://github.com/gjtorikian/html-proofer/issues/378.

Ensure lack of slash in error messages

---

README.md

README.md states that the log file is called *tmp/.htmlproofer*. It should be *tmp/.htmlproofer/cache.log*.

Update README.md to reflect correct cache.log path

---

bin/htmlproofer
lib/html-proofer/cache.rb
lib/html-proofer/runner.rb
lib/html-proofer/utils.rb
spec/html-proofer/cache_spec.rb
spec/spec_helper.rb

This PR will add a `--storage-dir` option where you can configure the directory where the cache log file will be read from and written to.
I took the liberty to update the cache specs a bit to be more idiomatic RSpec/Ruby. Most of the change was required because the cache log location is no longer a constant nor can it be injected via stubbing a constant.
Fixes https://github.com/gjtorikian/html-proofer/issues/369

Make cache storage directory configurable

---

lib/html-proofer/configuration.rb

If you can't even connect to the server in 10 seconds (5 internet-years), then fail that connection.
This should solve many people's problems with `htmlproofer` crashing their Travis builds.
The default are more than reasonable. And of course people can override the defaults by using the Ruby API.

Set Typhoeus connection timeout, fixes #231, fixes #340

---

lib/html-proofer/check/links.rb
spec/html-proofer/fixtures/links/quote.html
spec/html-proofer/links_spec.rb

Having an id containing a quote is not allowed in HTML5. Having a quote currently crashes the link checking. This fix should solve that.

Escape quotes in anchors

---

lib/html-proofer/check/links.rb
spec/html-proofer/fixtures/links/cors_not_provided.html
spec/html-proofer/fixtures/links/integrity_and_cors_not_provided.html
spec/html-proofer/fixtures/links/integrity_and_cors_provided.html
spec/html-proofer/fixtures/links/integrity_not_provided.html
spec/html-proofer/fixtures/links/local_stylesheet.html
spec/html-proofer/links_spec.rb

Check for SRI/CORS in CSS files

---

html-proofer.gemspec
lib/html-proofer/version.rb

Do to a security [vulnerability in `nokogiri`](https://github.com/sparklemotion/nokogiri/issues/1615), this PR updates to that gem to the next safe version, `1.7`. 
I also updated the `html-proofer` version to `3.7.0`.
cc @gjtorikian

Update nokogiri to v1.7

---

lib/html-proofer/element.rb
spec/html-proofer/fixtures/links/base_no_href.html
spec/html-proofer/links_spec.rb

[`<base>`](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element) can have `href` and/or `target` attributes. Currently, `href` is not present obtains:
> htmlproofer 3.6.0 | Error:  Can't convert NilClass into String.
This PR allows `<base>` to not have an `href` attribute.

handle base without href

---

lib/html-proofer/check/links.rb
spec/html-proofer/fixtures/links/githubHash.html
spec/html-proofer/fixtures/links/topHashInternal.html
spec/html-proofer/fixtures/vcr_cassettes/links/githubHash_html_log_level_error_type_file_.yml
spec/html-proofer/links_spec.rb

Per the HTML5 spec:
> If `fragid` is an ASCII case-insensitive match for the string `top`, then the indicated part of the document is the top of the document
https://www.w3.org/TR/html5/single-page.html#scroll-to-fragid
/cc #118

support links to the #top of pages

---

README.md

This change to the project scope clarifies that "advanced" usage of this project will require using Ruby.
It would allow us to close issues as out of scope:
* #408 
* #379 
* #194 
Also it will allow us to accept a change to the README which would simplify the recommended use case (command line) while allowing further, advanced discussion in a separate file or wiki like https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis

Document difference between command line and Ruby implementation

---

lib/html-proofer/check/favicon.rb
spec/html-proofer/favicon_spec.rb
spec/html-proofer/fixtures/favicon/jekyll_redirect_from.html

Closes https://github.com/gjtorikian/html-proofer/issues/446, though it is extraordinarily brittle, there's not much else that can be done.

Ignore Jekyll redirect_from template from favicon check

---

lib/html-proofer/check/favicon.rb

An improvement on #448 that specifically checks for a zero-time refresh meta tag.

More robust redirect detection

---

html-proofer.gemspec
lib/html-proofer/log.rb

Colored is no longer maintained. Resolves #449, and will prevent a bunch of outdated dependency warnings for people using html-proofer.
There currently aren't any tests for the `Log` class, as far as I can see. Would you want some added in order to merge this?

Change to use colorize gem

---

html-proofer.gemspec

Nokogiri 1.8.0 and below contains a vulnerability (http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-9050, https://security.gentoo.org/glsa/201711-01) reported by GitHub via e-mail today. This upgrades nokogiri to the new, patched version.
I'm not a Ruby expert, so this is mostly just to get the ball rolling. I don't think I would know what to do if it fails…

Update nokogiri to ~> 1.8.1 (CVE-2017-9050)

---

lib/html-proofer/url_validator.rb
spec/html-proofer/fixtures/links/brokenLinkExternal.html
spec/html-proofer/links_spec.rb

It doesn't seem to make much sense to `chomp` the URL in the debug output.
If I'm looking at the debug logs and it's saying that a particular URL has an error. I expect it to tell me the exact string of the URL that has the error -not a string that has been manipulated.

Remove chomp URL from debug output

---

html-proofer.gemspec
lib/html-proofer/cache.rb
lib/html-proofer/url_validator.rb
spec/html-proofer/links_spec.rb

And upgrading typhoeus
to solve https://github.com/gjtorikian/html-proofer/pull/398#issuecomment-349415894

dropping url.chomp('/') which cause 301s

---

.gitignore
README.md

While trying out I found that the example code for a custom check in the README does not actually run.   It's mainly a word order typo.   
I added the check for nil to the oktopost example, too because it's suspectible to the same issues - but that's optional and could be left out for conciseness sake. 
If you want you can take over the .gitignore addition for JetBrains RubyMine IDE users, too. But that's just cosmetics.

Improve / Fix Example Code in README

---

README.md
bin/htmlproofer
lib/html-proofer.rb
lib/html-proofer/check/links.rb
lib/html-proofer/configuration.rb
lib/html-proofer/element.rb
spec/html-proofer/links_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/474.

Allow skipping the `href` requirement

---

lib/html-proofer/utils.rb
spec/html-proofer/utils_spec.rb

I was trying out 3.9.0 and ran into the following error: `utils.rb:11:in `read': Is a directory @ io_fread`
This fixes that so it won't blow up anymore. 
<details>
<summary>Traceback</summary>
```
Traceback (most recent call last):
27: from /usr/local/bin/htmlproofer:23:in `<main>'
26: from /usr/local/bin/htmlproofer:23:in `load'
25: from /usr/local/lib/ruby/gems/2.5.0/gems/html-proofer-3.7.6/bin/htmlproofer:9:in `<top (required)>'
24: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
23: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
22: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
21: from /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/merce …
```

don't File.read directories

---

spec/html-proofer/utils_spec.rb

The build is broking on Rubocop because of this. So I'm removing these trailing whitespaces.

Remove trailing whitespaces

---

README.md
bin/htmlproofer

Previous description is not clear about if it allows only "#" or also strings starting with "#". My version seems more clear for me. :-)

Changed description of allow_hash_href option

---

.gitignore
html-proofer.gemspec
lib/html-proofer.rb
lib/html-proofer/check/links.rb
spec/html-proofer/favicon_spec.rb
spec/html-proofer/fixtures/favicon/cors_not_needed.html
spec/html-proofer/fixtures/vcr_cassettes/favicon/cors_not_needed_html_check_sri_true_log_level_error_type_file_.yml
spec/html-proofer/scripts_spec.rb

Should close https://github.com/gjtorikian/html-proofer/issues/481

 Add more skippable rel types

---

lib/html-proofer/check/links.rb
spec/html-proofer/fixtures/links/integrity_and_cors_pagination_rels.html
spec/html-proofer/links_spec.rb

Will fix #495.
Kinda blowed away my previous fork (https://github.com/gjtorikian/html-proofer/pull/496#issue-228174884) - I wanted to write some checks around pagination links, but I don't have setup to run tests locally (maybe when I'll have normal setup I'll try to do this). 
I've added pagination rels to ignore and writed simple test for it. @Floppy, what do you think?

Ignoring sri for pagination rels 

---

.travis.yml

Travis now uses ruby 2.6.0 via rvm for the build environment

Let Travis build with ruby 2.6.0

---

README.md
bin/htmlproofer
lib/html-proofer.rb
spec/html-proofer/parse_json_option_spec.rb

Hi all,
First off -- thanks for a great tool! It's useful enough that I [went out of my way to use it for my Jekyll blog](https://seankilleen.com/2018/09/using-wsl-to-make-ruby-play-nice/) recently. 
I noticed that there appear to have been some requests previously to support Typhoeus options from the command-line. I would also find this quite useful, even though we can currently use a ruby script to obtain the same things.
I figured I would take a shot at contributing this feature as an exercise to expand my own ruby capabilities as well as contribute something back that I and others have expressed interest in.
Along the way, I am open to guidance and direction. And I intend to ensure the specs are covered to your satisfaction.
* Enable users to pass `--typhoeus-config CONFIG` with a …

Support Typhoeus options from command line

---

README.md
lib/html-proofer/middleware.rb
lib/html-proofer/runner.rb
spec/html-proofer/fixtures/vcr_cassettes/links/integrity_and_cors_pagination_rels_html_check_sri_true_log_level_error_type_file_.yml
spec/html-proofer/middleware_spec.rb

Sample usage in a Rails app: Add to `config/application.rb`
config.middleware.use HTMLProofer::Middleware if Rails.env.test?
config.middleware.use HTMLProofer::Middleware if Rails.env.development?
This will raise an error at runtime if your HTML is invalid. 
Particularly helpful for projects which have extensive CI.

Add rack middleware for proofing HTML at runtime

---

bin/htmlproofer

This overwrites the defaults the proofer later attempts to merge in.
Fixes https://github.com/gjtorikian/html-proofer/issues/524.

Don't set blank hash values

---

lib/html-proofer/check/links.rb
spec/html-proofer/fixtures/links/link_with_me.html
spec/html-proofer/fixtures/vcr_cassettes/links/link_with_me_html_check_sri_true_log_level_error_type_file_.yml
spec/html-proofer/fixtures/vcr_cassettes/links/redirected_error_html_log_level_error_type_file_.yml
spec/html-proofer/links_spec.rb

This is the alternative solution for the addition in #528. The SRI spec only applies to `<link rel='stylesheet'>`, so this PR only applies the check to those. This means we don't need an ever-expanding whitelist of rel types, but can easily add more into the check.

Check only stylesheet link rels rather than whitelisting other rels

---

lib/html-proofer/runner.rb
spec/html-proofer/proofer_spec.rb

👋 This pull request adds a reader for `@failures` so users can access them directly, and use the `Issue` to construct their report if they wish to do so, like what #523 wanted to do. 
In our use case, we mostly want to avoid Proofer from raising a generic `RuntimeError`, and so we will be printing out the errors ourselves. I initially accessed `#failed_tests` for this, but found that we'd want to group results with path. Since `#failed_test` gives us `issue.to_s`, we will have to manually parse it back. Having `#failures` would be more convenient and gives developers flexibility around reporting.
It'd also be good to decouple the checks in `#run` into another method so it can be called without raise/logger. I thought I'd start small for now. Thoughts?
cc @gjtorikian 😬

Allow accessing list of issues directly

---

README.md
bin/htmlproofer
lib/html-proofer/element.rb
spec/html-proofer/fixtures/links/working_root_link_internal.html
spec/html-proofer/links_spec.rb

Before: When running .check_file(...) on a file in a non-flat file-hierarchy, it is not possible to specify the root folder from which folder the file is being served. Instead the specified file's folder is assumed as root.
This leads to false positives when refering to a file outside of the specified file's folder.
After: enable specifying a root_dir from where the file is served, when a link begining with slash is found, html-proofer now checks the root_dir for any refered files, so all internal links can be resolved properly.

feat: enable specifying a root folder

---

.rubocop.yml
Rakefile
bin/htmlproofer
html-proofer.gemspec
lib/html-proofer.rb
lib/html-proofer/cache.rb
lib/html-proofer/check.rb
lib/html-proofer/check/favicon.rb
lib/html-proofer/check/html.rb
lib/html-proofer/check/images.rb
lib/html-proofer/check/links.rb
lib/html-proofer/check/opengraph.rb
lib/html-proofer/configuration.rb
lib/html-proofer/element.rb
lib/html-proofer/issue.rb
lib/html-proofer/middleware.rb
lib/html-proofer/runner.rb
lib/html-proofer/url_validator.rb
lib/html-proofer/utils.rb
lib/html-proofer/version.rb
spec/html-proofer/cache_spec.rb
spec/html-proofer/command_spec.rb
spec/html-proofer/fixtures/links/broken_root_link_internal.html
spec/html-proofer/fixtures/links/working_root_link_internal.html
spec/html-proofer/images_spec.rb
spec/html-proofer/links_spec.rb
spec/html-proofer/middleware_spec.rb
spec/spec_helper.rb

I found some confusing code and followed it down the rabbit hole. I hope this will make the code more maintainable.

Fix: internal link misrepresented and misused

---

lib/html-proofer/check/links.rb
lib/html-proofer/element.rb
lib/html-proofer/middleware.rb
lib/html-proofer/utils.rb
spec/html-proofer/links_spec.rb
spec/html-proofer/utils_spec.rb

Based on #539 
Change from !remote? -> internal? and handle all the domino effects of this.

refactor: use internal instead of not external

---

lib/html-proofer/element.rb
spec/html-proofer/fixtures/links/relative_hash.html
spec/html-proofer/links_spec.rb

Fixes https://github.com/gjtorikian/html-proofer/issues/544

Fix: internal hash links

---

.gitignore
.rubocop.yml
.travis.yml
lib/html-proofer.rb
lib/html-proofer/log.rb
lib/html-proofer/runner.rb

Seems like the logging was affected by new Ruby 2.7 changes, I suspect around `fetch`, because the issue is coming from Yell.
Switching out of passing an array of symbols seems to have fixed this.
Closes https://github.com/gjtorikian/html-proofer/issues/549.

Fix mysterious new ruby issues

---

README.md
bin/htmlproofer
lib/html-proofer/check/html.rb
lib/html-proofer/configuration.rb
lib/html-proofer/middleware.rb
lib/html-proofer/utils.rb
spec/html-proofer/command_spec.rb
spec/html-proofer/fixtures/html/parse_failure.html
spec/html-proofer/html_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/553

Add tests demonstrating parse failure

---

README.md
lib/html-proofer/runner.rb
lib/html-proofer/url_validator.rb
spec/html-proofer/runner_spec.rb

This PR adds the `HTMLProofer::Runner#before_request` method so the `Typhoeus::Request` object can be modified before the request is executed. I'm not happy about the accompanying spec, so any input on how to improve it is welcome.
Fixes #86.

Add HTMLProofer::Runner#before_request

---

lib/html-proofer/runner.rb
spec/html-proofer/cache_spec.rb
spec/html-proofer/fixtures/cache/.not_within_date_internal.log

Closes https://github.com/gjtorikian/html-proofer/issues/604.

Correct internal links when pulled from outdated cache

---

.github/workflows/ci.yml
.rubocop.yml
lib/html-proofer.rb
lib/html-proofer/runner.rb
lib/html-proofer/url_validator.rb
spec/html-proofer/fixtures/links/hash/inner.html
spec/html-proofer/proofer_spec.rb
spec/spec_helper.rb

Closes https://github.com/gjtorikian/html-proofer/issues/608

Never needed to raise

---

.github/workflows/ci.yml
.github/workflows/lint.yml
html-proofer.gemspec

[Ruby 3.0 has been released](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/) 🎉 
This PR makes the following changes:
* add Ruby 3.0 to build matrix
* use Ruby 3.0 for linting
* changes `gem.required_ruby_version` to `>= 2.4.10` and `< 4.0`.
~~The changes `gem.required_ruby_version` are TBD. Allowing everything above `2.4.10` (oldest Ruby in build matrix) looked like the simplest solution.~~

Allow usage of Ruby 3.0

---

lib/html-proofer/element.rb
lib/html-proofer/middleware.rb
spec/html-proofer/middleware_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/621

Correct link ignore regexp

---

lib/html-proofer/cache.rb
lib/html-proofer/check/links.rb
lib/html-proofer/element.rb
lib/html-proofer/runner.rb
lib/html-proofer/url_validator.rb
spec/html-proofer/cache_spec.rb
spec/html-proofer/fixtures/cache/.external.log
spec/html-proofer/fixtures/cache/.internal_and_external.log
spec/html-proofer/fixtures/cache/external_example.html
spec/html-proofer/fixtures/cache/internal_and_external_example.html
spec/html-proofer/fixtures/vcr_cassettes/cache/external_example_html_external_only_true_links_only_true_cache_timeframe_1d_cache_file_external_log_storage_dir_spec/html-proofer/fixtures/cache_log_level_error_type_file_.yml
spec/html-proofer/fixtures/vcr_cassettes/cache/internal_and_external_example_html_external_only_true_links_only_true_cache_timeframe_1d_cache_file_internal_and_external_log_storage_dir_spec/html-proofer/fixtures/cache_log_level_error_type_file_.yml

Closes https://github.com/gjtorikian/html-proofer/issues/620

Handle internal & external cache merging

---

bin/htmlproofer
lib/html-proofer/configuration.rb
spec/html-proofer/parse_json_option_spec.rb

Related: https://github.com/gjtorikian/html-proofer/issues/131
Thanks for considering, and thanks for all your work on maintaining this tool! :)

Add --hydra-config flag to override concurrency from CLI

---

README.md
html-proofer.gemspec
lib/html-proofer/utils.rb

Nokogiri 1.12 merged all of the code from Nokogumbo and thus Nokogumbo
is no longer needed.

Replace Nokogumbo with Nokogiri

---

README.md

I think this might resolve the issues seen in #581 (which is already closed) by allowing cookies in typhoeus.
Adds some snippets to the README to show how to specify a cookie file (from ruby (untested) and the command line) and user agent (from the command line).
I spent some time figuring this out and thought that the information should be in the README for future users. Let me know what you think.

Add typhoeus-config user agent and cookies snippets to the README

---

spec/spec_helper.rb

We are in the midst of the transition from Ruby 2.7 to 3.0 and run the tests with both versions. But the shebang line in `bin/htmlproofer` will always resolve to the default version, not to the used Ruby version. This small patch makes sure to run it with the Ruby binary belonging to the used environment.

Run htmlproofer and precede it with the correct ruby binary

---

lib/html-proofer/runner.rb

Hello. This simple patch applies a `uniq!` call right before the problems printer to remove duplicate issue objects from the array.
This should mitigate the noise from the duplicate issue problem self stacking coming from the `.concat` calls.
I setup a set stub repo showing this off, https://github.com/uberfuzzy/proofer-dupe-test
The cause is the places where new issues are being collected, and added to the global collectors using `.concat`
This is what is roughly what is happening from what I've been able to trace down with a lot of debug prints:
- Issue A is found
- Issue added to check object's issues array (issues now `[A]`)
- Issues array is concat'd onto the large problem array. (problems now `[A]`)
- Issue B is found.
- Issue added to check object's issues array (issues now …

Apply Uniq filter to remove duplicate issues

---

lib/html_proofer/runner.rb
spec/html-proofer/fixtures/links/multiple_links.html
spec/html-proofer/fixtures/vcr_cassettes/links/multiple_links_html_log_level_error_type_file_.yml
spec/html-proofer/links_spec.rb
spec/html-proofer/proofer_spec.rb

Fixes #695
* Unit test revealing issue #695
* Fix logic for checking cached failures and managing new url metadata

Fix internal cache metadata check

---

.github/workflows/ci.yml
.github/workflows/lint.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

lib/html_proofer/attribute/url.rb
spec/html-proofer/links_spec.rb

This was erroneously taken out!
Closes https://github.com/gjtorikian/html-proofer/issues/718.

Restore `follow_location`

---

README.md

This PR updates the README to use `--ignore-urls` instead of `--url-ignore` for compatibility with HTMLProofer v4.

Change --url-ignore to --ignore-urls in README.md

---

bin/htmlproofer
spec/html-proofer/command_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/735

clarify CLI booleans

---

lib/html_proofer/check/images.rb
spec/html-proofer/fixtures/images/multiple_srcset-pixel-density.html
spec/html-proofer/images_spec.rb

The previous fix to #724 didn't handle this situation:
`srcset="test.webp 1.5x, test2.webp 2x"`
This PR should fix this, add a new test case, and hopefully remove some code duplication as a nice bonus.

Srcsets - better handling of multiple srcsets

---

lib/html_proofer/check/images.rb
lib/html_proofer/check/links.rb
spec/html-proofer/fixtures/images/src_set_check_pass.html
spec/html-proofer/fixtures/images/src_set_missing_image.html
spec/html-proofer/fixtures/images/srcset_picture_pixel-density.html
spec/html-proofer/fixtures/images/srcset_picture_pixel-density_broken.html
spec/html-proofer/images_spec.rb

As discussed in comments to #744 - this change shifts 'source' elements to be handled by the code path for checking images.
A number of other small changes to tests needed to be made also - this was because these tests were referring to non-existent images in tests that did not relate to the URL not being to a valid image. These have been updated to point to images that actually exist.

Switch 'source' elements to use image check code path

---

README.md

* Wrongly specified as `swap_url`
* Using `data-src` as a more meaningful case than `srcset`, as the latter is in any case allowed instead of `src`
See also https://github.com/gjtorikian/html-proofer/issues/754#issuecomment-1214425422

Fix and improve swap_attribute README example

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.rubocop.yml
html-proofer.gemspec
lib/html_proofer/check/images.rb
spec/html-proofer/attribute/url_spec.rb
spec/html-proofer/cache_spec.rb
spec/html-proofer/command_spec.rb
spec/html-proofer/element_spec.rb
spec/html-proofer/favicon_spec.rb
spec/html-proofer/images_spec.rb
spec/html-proofer/links_spec.rb
spec/html-proofer/maliciousness_spec.rb
spec/html-proofer/opengraph_spec.rb
spec/html-proofer/parse_json_option_spec.rb
spec/html-proofer/proofer_spec.rb
spec/html-proofer/scripts_spec.rb
spec/html-proofer/utils_spec.rb

Ruby 3.1 has some optimizations for Windows; since I'm breaking a new major release out, it makes sense to lift the restrictions here a bit. Plus, I want to use `async` instead of `parallel`, which is a Ruby 3+ addition.

Lock to >= Ruby 3.1

---

Rakefile
lib/html_proofer.rb
lib/html_proofer/url_validator/internal.rb

By collecting non-duplicate hashes by file and calling the time-consuming `create_nokogiri()` only once per file.
Should address #768
See the attached output ([htmlproofer-output.txt](https://github.com/gjtorikian/html-proofer/files/9637319/htmlproofer-output.txt)) of running the internal link checks on the `build-site` site artifact discussed in https://github.com/gjtorikian/html-proofer/issues/768#issuecomment-1255628337, via
```sh
htmlproofer --disable-external true --log-level debug --checks Links  build-site/
```
- The total execution is now around 10 min
- The output shows also the additional info / debug logs that help tracking how much htmlproofer is doing for checking internal links / hashes
- in particular, it reflects the new approach of checking internal hashes by target file …

Optimize checking internal link hashes in target files

---

spec/html-proofer/links_spec.rb

Delete `erstiebegrüßung.html` from Git and create it with code in the specs instead. Fixes #771.

Create erstiebegrüßung.html from code

---

.github/workflows/lint.yml
.github/workflows/test.yml
lib/html_proofer/configuration.rb
lib/html_proofer/runner.rb
spec/html-proofer/command_spec.rb
spec/spec_helper.rb

Fixes https://github.com/gjtorikian/html-proofer/issues/775#issuecomment-1298799143

Accept regexp values for ignore-files via CLI

---

.github/dependabot.yml
.github/workflows/automerge.yml
.github/workflows/lint.yml
.github/workflows/tag_and_release.yml
.github/workflows/test.yml
Gemfile
lib/html_proofer/configuration.rb
lib/html_proofer/version.rb
script/generate_changelog
spec/html-proofer/command_spec.rb

Closes https://github.com/gjtorikian/html-proofer/issues/779

Address some typos

---

Rakefile
lib/html_proofer/check/links.rb
lib/html_proofer/log.rb
lib/html_proofer/reporter.rb
lib/html_proofer/version.rb
spec/html-proofer/fixtures/links/multiple_mailto_links.html
spec/html-proofer/links_spec.rb

Should close https://github.com/gjtorikian/html-proofer/issues/796

Support multiple email addresses in `mailto`

---

spec/html-proofer/check/links_spec.rb
spec/html-proofer/fixtures/links/hash_nonascii.html
spec/html-proofer/fixtures/links/hash_nonascii_dir/source/index.html
spec/html-proofer/fixtures/links/hash_nonascii_dir/target/index.html

This adds a test for the false-negative failures seen in https://github.com/gjtorikian/html-proofer/issues/757 - the root cause was an interaction between the (now-removed) regexp in the `clean_url!` method and Addressable::URI's `normalize`. The test passes now that https://github.com/gjtorikian/html-proofer/pull/820 is merged but the test should prevent regressions in the future.

Check utf8 relative anchors
