lib/html/proofer/checkable.rb, lib/html/proofer/checks/images.rb, spec/html/proofer/fixtures/images/srcSetCheck.html, spec/html/proofer/fixtures/images/srcSetIgnorable.html, spec/html/proofer/fixtures/images/srcSetMissingAlt.html, spec/html/proofer/fixtures/images/srcSetMissingImage.html, spec/html/proofer/images_spec.rb
Fixes https://github.com/gjtorikian/html-proofer/issues/70, fixes https://github.com/gjtorikian/html-proofer/issues/149.
=> Add support for srcset

lib/html/proofer.rb, lib/html/proofer/checkable.rb, lib/html/proofer/checks/links.rb, lib/html/proofer/url_validator.rb, lib/html/proofer/utils.rb, spec/html/proofer/links_spec.rb, spec/html/proofer/utils_spec.rb
Mostly, this gets it working for an array of links.
=> Improve support for the href_swap feature

lib/html/proofer/checkable.rb, spec/html/proofer/fixtures/links/attributeWithDash.html, spec/html/proofer/links_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/158.
@mietek You keep logging them, I'll keep fixing them. :wink:
=> Translate attributes with dashes into underscores

lib/html/proofer/url_validator.rb
=> Add params to UrlValidator#handle_timeout per its usage

lib/html/proofer/url_validator.rb
Addresses https://github.com/gjtorikian/html-proofer/issues/162#issuecomment-72347764
=> Add missing argument

html-proofer.gemspec
From what I see the 0.7.x has some improvements and fix some bugs.
=> Upgrade Typhoeus to 0.7

.travis.yml, Gemfile, README.md, spec/spec_helper.rb
Code Climate detects test coverage and code complexity on every pull request. This helps to improve the overall code quality.
=> Add Code Climate

lib/html/proofer/checkable.rb, spec/html/proofer/checkable_spec.rb
This is another turn to fix #173 (first try: #179).
=> Accept namespace attributes

README.md
=> correct --ignore option

README.md
This answers one of the most asked questions. Source: https://github.com/typhoeus/typhoeus/issues/325#issuecomment-25432261
=> Explain how to ignore certificates

spec/html/proofer_spec.rb
This should fix the failures for the sorting test https://travis-ci.org/gjtorikian/html-proofer/jobs/68576491
=> Wikipedia sends 301 now

bin/htmlproof
=> Add the url_ignore option to the binary

README.md, bin/htmlproof, lib/html/proofer.rb, lib/html/proofer/checks/links.rb, spec/html/proofer/fixtures/links/non_https.html, spec/html/proofer/fixtures/vcr_cassettes/links/non_https_html.yml, spec/html/proofer/fixtures/vcr_cassettes/links/non_https_html_enforce_https_true_.yml, spec/html/proofer/links_spec.rb
This will close https://github.com/gjtorikian/html-proofer/issues/252.
=> Add support for enforcing HTTPS links

bin/htmlproof, spec/html/proofer_spec.rb
Should close https://github.com/gjtorikian/html-proofer/issues/261.
=> Pass along `ignore_script_embeds` in bin

lib/html/proofer/utils.rb
An even better implementation for https://github.com/gjtorikian/html-proofer/pull/273. Not sure what I was originally thinking!
=> Just a single regex will do

lib/html/proofer/checks/links.rb, spec/html/proofer/fixtures/links/Kernel.html, spec/html/proofer/fixtures/links/encodingLink.html, spec/html/proofer/links_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/190
=> Search for decoded internal IDs, too

spec/html-proofer/images_spec.rb, spec/html-proofer/scripts_spec.rb, spec/html/proofer/fixtures/images/replaceAbsUrlSrc.html, spec/html/proofer/fixtures/scripts/script_abs_url.html
Plucked from https://github.com/gjtorikian/html-proofer/pull/178, and modified to fit Proofer 3.0.
=> Better tests for URL swap

bin/htmlproofer, lib/html-proofer/cache.rb, lib/html-proofer/configuration.rb, lib/html-proofer/url_validator.rb, spec/html-proofer/cache_spec.rb, spec/html-proofer/fixtures/vcr_cassettes/links/brokenLinkExternal_html_cache_timeframe_30d_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/www_github_com_foofoofoo_biz_log_level_error_type_links_.yml, spec/spec_helper.rb
Fixes some intermittent test failures in the 3.0 branch by properly handling missing external hashes.
=> Cache improvements

lib/html-proofer/check/html.rb, spec/html-proofer/fixtures/html/ignore_namespace.html, spec/html-proofer/html_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/306.
=> Ignore namespaces in tags

README.md, bin/htmlproofer, lib/html-proofer/check/html.rb, lib/html-proofer/configuration.rb, spec/html-proofer/fixtures/html/single_amp.html, spec/html-proofer/html_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/328.
=> Do not blow up on missing ampersand names

README.md
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
=> Add Atom Flight Manual to real-life examples

.travis.yml, html-proofer.gemspec
Closes https://github.com/gjtorikian/html-proofer/issues/354.
=> Support newer ActiveSupport

README.md, lib/html-proofer/check.rb, lib/html-proofer/check/favicon.rb, lib/html-proofer/check/images.rb, lib/html-proofer/check/links.rb, lib/html-proofer/check/scripts.rb, lib/html-proofer/issue.rb, spec/html-proofer/proofer_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/317.
=> Report on the content of the error, when able

lib/html-proofer/check/links.rb, lib/html-proofer/configuration.rb, lib/html-proofer/element.rb, lib/html-proofer/url_validator.rb, spec/html-proofer/fixtures/links/hash_href.html, spec/html-proofer/images_spec.rb, spec/html-proofer/links_spec.rb, spec/html-proofer/opengraph_spec.rb, spec/html-proofer/scripts_spec.rb
- add support for # links on other pages, e.g. /about#Team should be valid
- do not count img without alt tags if aria-hidden="true"
https://github.com/gjtorikian/html-proofer/issues/367
=> Improvements to html-proofer:

bin/htmlproofer, lib/html-proofer/check/scripts.rb, lib/html-proofer/configuration.rb, lib/html-proofer/element.rb, spec/html-proofer/fixtures/scripts/cors_not_provided.html, spec/html-proofer/fixtures/scripts/integrity_and_cors_not_provided.html, spec/html-proofer/fixtures/scripts/integrity_and_cors_provided.html, spec/html-proofer/fixtures/scripts/integrity_not_provided.html, spec/html-proofer/scripts_spec.rb
close https://github.com/gjtorikian/html-proofer/issues/382
=> Check for SRI/CORS links #382

README.md
From https://github.com/gjtorikian/html-proofer/issues/381.
=> Add Travis CI caching example

README.md, lib/html-proofer/element.rb, lib/html-proofer/url_validator.rb, spec/html-proofer/fixtures/links/ignored_by_parent.html, spec/html-proofer/fixtures/opengraph/url-broken.html, spec/html-proofer/fixtures/vcr_cassettes/links/ignored_by_parent_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/opengraph/url-broken_html_check_opengraph_true_log_level_error_type_file_.yml, spec/html-proofer/links_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/370.
=> Let the parent element mark the ignorability of content

lib/html-proofer/url_validator.rb, spec/html-proofer/fixtures/links/do_not_cgi_encode.html, spec/html-proofer/fixtures/vcr_cassettes/links/attributeWithDash_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/bad_external_links_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/brokenLinkExternal_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/do_not_cgi_encode_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/file_foo_extension_foo_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/link_missing_protocol_invalid_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/non_https_html_enforce_https_true_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/non_https_html_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/links/non_standard_characters_html_log_level_error_type_file_.yml, spec/html-proofer/links_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/385.
=> Only normalize a URL when it is actually needed

README.md, Rakefile
Thanks to @fulldecent for the idea. Could I get your review/opinion here?
=> Add some words on project scope

README.md, html-proofer.gemspec, spec/html-proofer/links_spec.rb, spec/spec_helper.rb
codecov helps find untested code
=> Codecov and timeout test

lib/html-proofer/check/links.rb
=> check only 'link' tag links

lib/html-proofer/check/images.rb, lib/html-proofer/url_validator.rb, spec/html-proofer/fixtures/images/empty_image_alt_text.html, spec/html-proofer/images_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/416
=> Fix the `empty_alt_ignore` option

lib/html-proofer/url_validator.rb, spec/html-proofer/fixtures/links/empty_href.html, spec/html-proofer/links_spec.rb
=> Replace null chars with empty ones

lib/html-proofer/element.rb, spec/html-proofer/fixtures/links/no_html_extension.html
=> Make assume_extension work with a directory with the same name

bin/htmlproofer, lib/html-proofer/runner.rb
This wasn't *quite* running correctly. Closes https://github.com/gjtorikian/html-proofer/issues/504.
=> Tweak `--as-links` cli

html-proofer.gemspec, lib/html-proofer/log.rb
This avoids GPL copyright issues.
Addresses https://github.com/gjtorikian/html-proofer/issues/449#issuecomment-484908367
=> Switch coloring gems

html-proofer.gemspec, lib/html-proofer/cache.rb, lib/html-proofer/check/favicon.rb, lib/html-proofer/check/links.rb, lib/html-proofer/element.rb, lib/html-proofer/middleware.rb
=> Remove ActiveRecord requirement

html-proofer.gemspec, lib/html-proofer/cache.rb, spec/html-proofer/cache_spec.rb
An attempt to resolve https://github.com/gjtorikian/html-proofer/issues/535. I don't like pulling in spurious dependencies, and the maths here isn't as hard as I thought it would be.
=> Do time duration yourself

lib/html-proofer/check/opengraph.rb, lib/html-proofer/element.rb, lib/html-proofer/middleware.rb, spec/html-proofer/command_spec.rb, spec/html-proofer/fixtures/links/at_sign.html, spec/html-proofer/fixtures/links/at_sign_ignorable.html, spec/html-proofer/links_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/576
=> Allow for at-signs

README.md
Previous one is 2 years old archived project, new one is automatically updated.
=> Replaced reccomanded Docker image

lib/html-proofer/check/links.rb, spec/html-proofer/fixtures/links/source.html, spec/html-proofer/fixtures/vcr_cassettes/links/source_html_log_level_error_type_file_.yml, spec/html-proofer/links_spec.rb
Should close https://github.com/gjtorikian/html-proofer/issues/589
=> test source tags

README.md, bin/htmlproofer, lib/html-proofer/element.rb, lib/html-proofer/runner.rb, spec/html-proofer/command_spec.rb, spec/html-proofer/fixtures/links/root_folder/documentation-from-my-project/root_link.html
Should close https://github.com/gjtorikian/html-proofer/issues/587
=> Let `root_dir` work when running on directories

.gitignore, lib/html-proofer/check.rb, lib/html-proofer/check/links.rb, lib/html-proofer/runner.rb, spec/html-proofer/fixtures/links/hashes/doc/hcl/index.html, spec/html-proofer/fixtures/links/hashes/downloads/index.html, spec/html-proofer/fixtures/links/hashes/support/index.html, spec/html-proofer/links_spec.rb
Should close https://github.com/gjtorikian/html-proofer/issues/602
=> Broken hash reporting

lib/html-proofer/check/links.rb, lib/html-proofer/element.rb, spec/html-proofer/fixtures/links/bad_formatting.html, spec/html-proofer/links_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/615
=> Catch bad URLs

lib/html-proofer/cache.rb, lib/html-proofer/runner.rb, lib/html-proofer/url_validator.rb, spec/html-proofer/cache_spec.rb, spec/html-proofer/fixtures/cache/.removed_link.log, spec/html-proofer/fixtures/cache/some_link.html, spec/html-proofer/fixtures/vcr_cassettes/cache/external_example_html_external_only_true_links_only_true_cache_timeframe_1d_cache_file_removed_link_log_storage_dir_spec/html-proofer/fixtures/cache_log_level_error_type_file_.yml, spec/html-proofer/fixtures/vcr_cassettes/cache/some_link_html_external_only_true_links_only_true_cache_timeframe_1d_cache_file_removed_link_log_storage_dir_spec/html-proofer/fixtures/cache_log_level_error_type_file_.yml
This should fix https://github.com/gjtorikian/html-proofer/issues/625.
=> Do a better job preserving cache logic

bin/htmlproofer, lib/html-proofer/configuration.rb, spec/html-proofer/command_spec.rb, spec/html-proofer/fixtures/vcr_cassettes/links/github_hash_html_typhoeus_verbose_true_headers_User-Agent_Mozilla/5_0_compatible_My_New_User-Agent_log_level_error_type_file_.yml, spec/html-proofer/proofer_spec.rb, spec/spec_helper.rb
=> Address wild double UA bug

.github/workflows/ci.yml, bin/htmlproofer, html-proofer.gemspec, lib/html-proofer/runner.rb, spec/html-proofer/command_spec.rb, spec/html-proofer/fixtures/cache/.runner.log, spec/spec_helper.rb
Closes https://github.com/gjtorikian/html-proofer/issues/644
=> Allow `--hydra-config` to symbolize opts

lib/html_proofer/check/images.rb, lib/html_proofer/element.rb, spec/html-proofer/fixtures/images/multiple_srcset_failure.html, spec/html-proofer/fixtures/images/multiple_srcset_success.html, spec/html-proofer/images_spec.rb
Closes https://github.com/gjtorikian/html-proofer/issues/313
=> Support multiple srcsets

README.md, bin/htmlproofer, lib/html_proofer/attribute/url.rb, lib/html_proofer/check/favicon.rb, lib/html_proofer/configuration.rb, lib/html_proofer/element.rb, spec/html-proofer/command_spec.rb, spec/html-proofer/fixtures/images/data_src_attribute.html, spec/html-proofer/images_spec.rb
cc https://github.com/gjtorikian/html-proofer/pull/630
=> Allow for custom attributes to be set

lib/html_proofer/cache.rb, spec/html-proofer/cache_spec.rb, spec/html-proofer/fixtures/cache/valid_link.html, spec/html-proofer/fixtures/cache/version_2/.broken_external_link.template, spec/html-proofer/fixtures/vcr_cassettes/cache/valid_link_html_cache_timeframe_1d_cache_file_version_2/_broken_external_link_json_storage_dir_spec/html-proofer/fixtures/cache_log_level_error_type_file_.yml
Closes https://github.com/gjtorikian/html-proofer/issues/683
=> Actually write the external link cache

html-proofer.gemspec, lib/html_proofer.rb
Should really close https://github.com/gjtorikian/html-proofer/issues/690.
=> Hide some more debuggery

lib/html_proofer.rb, lib/html_proofer/attribute/url.rb, lib/html_proofer/check.rb, lib/html_proofer/check/favicon.rb, lib/html_proofer/check/images.rb, lib/html_proofer/check/links.rb, lib/html_proofer/check/open_graph.rb, lib/html_proofer/check/scripts.rb, lib/html_proofer/configuration.rb, spec/html-proofer/attribute/url_spec.rb, spec/html-proofer/cli_reporter_spec.rb, spec/html-proofer/favicon_spec.rb, spec/html-proofer/fixtures/favicon/protocol_relative_favicon.html, spec/html-proofer/fixtures/opengraph/image-missing-protocol.html, spec/html-proofer/fixtures/opengraph/url-missing-protocol.html, spec/html-proofer/fixtures/scripts/script_missing_protocol.html, spec/html-proofer/images_spec.rb, spec/html-proofer/links_spec.rb, spec/html-proofer/opengraph_spec.rb, spec/html-proofer/scripts_spec.rb
=> Fail on protocol-relative urls

lib/html_proofer.rb, lib/html_proofer/configuration.rb, spec/html-proofer/proofer_spec.rb
Reverts gjtorikian/html-proofer#767 due to https://github.com/gjtorikian/html-proofer/issues/773
=> Revert "Validate options"

.github/workflows/ci.yml, README.md, html-proofer.gemspec, lib/html_proofer.rb, lib/html_proofer/configuration.rb, lib/html_proofer/runner.rb, spec/html-proofer/cli_reporter_spec.rb, spec/html-proofer/fixtures/vcr_cassettes/fixtures/links_extensions_xhtml_foo_log_level_error_type_directory_.yml, spec/html-proofer/proofer_spec.rb
Drop Parallel in favor of native async (> Ruby 3.1 only).
=> Native async

lib/html_proofer/attribute/url.rb, spec/html-proofer/fixtures/links/unicode_domain.html, spec/html-proofer/fixtures/vcr_cassettes/links/unicode_domain_html_log_level_error_type_file_.yml
Closes https://github.com/gjtorikian/html-proofer/issues/816
=> Remove unnecessary regexp
